# This workflow runs the `check_install` script with a few different versions of Python to make sure everything's in order.
# Based on: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  sanity:
    name: sanity check (Python ${{ matrix.python-version }})
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-java@v1
      with:
        java-package: jre
        java-version: '8'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Mock assignment dirs
      run: mkdir -p ../labs
    - name: Check install
      run: python check_install.py
